name: 'Formulae: Marker.io'
description: 'Provides a basic setup of Marker.io'
type: 'Site'
install:
  - key
  - markerio
config:
  actions:
    user.role.anonymous:
      ensure_exists:
        id: anonymous
      grantPermissions:
        - 'access markerio'
    user.role.authenticated:
      ensure_exists:
        id: authenticated
      grantPermissions:
        - 'access markerio'
